# fly.toml app configuration file for fly-log-shipper.
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstack-starter-log-shipper'
primary_region = 'fra'

[build]
  image = 'ghcr.io/superfly/fly-log-shipper:latest'

[env]
  SUBJECT = "logs.fullstack-starter-backend.>"

[http_service]
  internal_port = 8686
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
